### ISSUE TITLE
Progress display?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Juleps#39]
This is a really cool project, addressing one of the big issues I have with using Julia. I'm curious about when it'll be ready for testing. Would you consider opening a meta-issue with a few checkboxes that describe the current state of things, i.e. which pieces are missing and which are already working?

Apologies if it's too early for that.

**Comment by ChrisRackauckas** [comment]
For what project?

**Comment by eschnett** [comment]
D'oh. For Pkg3. I opened this ticket in the wrong location.

**Comment by ChrisRackauckas** [comment]
Nah, this is probably the right place. It's just this is for all Juleps. Probably need to mention you're asking about the Pkg3 Julep. It seems from the description of Stefan's talk that we'll get the details at JuliaCon.
