### ISSUE TITLE
Pkg.add(pkg) when pkg is installed

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/Juleps#42]
currently,
```julia
Pkg.rm("MyPackage"); Pkg.rm("MyPackage");
Pkg.add("MyPackage")
# takes some time
Pkg.add("MyPackage")
# takes some time -- which is silly
```
Pkg.add(pkg) should return immediately with eg "$(pkg) already added"  when pkg was add()ed already.

and 
- at least one of Pkg.add(xs) or Pkg.add([xs...]) should work (preferably both).
- the same for some other Pkg.cmds where it makes sense

**Comment by StefanKarpinski** [comment]
Is this a bug report about the old package manager or a feature request for the new one?

**Comment by JeffreySarnoff** [comment]
feature request

**Comment by StefanKarpinski** [comment]
Is the feature request roughly that package add/rm operations should be idempotent?

**Comment by JeffreySarnoff** [comment]
yes

**Comment by StefanKarpinski** [comment]
They already are in the described and implemented designs, so I think it's safe to close this, no?

**Comment by JeffreySarnoff** [comment]
yep
