### ISSUE TITLE
Pkg3: developing packages

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/Juleps#46]
Currently I'm organizing the packages which I develop by copying them to a folder with sym-links to `.julia`, see https://discourse.julialang.org/t/recommended-setup-for-developing-packages/5725 for a discussion.  I then started wondering how this would work with Pkg3 but did not find anything in the document, but got a bit confused how package-immutability and development would work together.

Maybe a section "Package development" should be added to:
https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md#operations

**Comment by StefanKarpinski** [comment]
I've reached a point where I'm implementing rather than updating the design doc; once things are generally working, I'll write up documentation rather than a Julep. You may want to try out and comment at https://github.com/StefanKarpinski/Pkg3.jl.

**Comment by mauro3** [comment]
That sounds very reasonable.  I'll see whether I find the time to test it.  Feel free to close this.

**Comment by StefanKarpinski** [comment]
Doesn't hurt to leave it open. I'll take a pass through all of these again later and ping people to see if they're satisfied with the solutions we end up with.
