### ISSUE TITLE
Pkg3: comparison with Guix

### ISSUE THREAD

**Issue by mvhulten** [JuliaLang/Juleps#48]
> Guix supports transactional upgrades and roll-backs, unprivileged package management, per-user profiles, [...] and takes a purely functional approach to package management

https://www.gnu.org/software/guix/
https://www.gnu.org/software/guix/manual/html_node/Package-Management.html

Guix is implemented in Scheme.  Julia uses Scheme as its parser.  All the ideas of Guix mentioned in the above quote appear in line with those of Julia.

I don't know if Pkg3 should be "like Guix", but I happen to be using, and interested in the development of, both Julia and Guix.  I wanted to be sure that all Pkg3 designers are well aware of Guix/Nix and possibly can use ideas/features (and maybe code) from the Guix project, or even collaborate.

**Comment by StefanKarpinski** [comment]
https://www.youtube.com/watch?v=-yUiLCGegJs

**Comment by mvhulten** [comment]
Good presentation (and it answers my issue)!
